### ISSUE TITLE
Unhandled exceptions in OnDocumentError cause pipeline to stall and documents be left behind

### ISSUE THREAD

**Issue by markawightman75** [waives/waives.net#55] opened 2018-09-10 16:52 UTC
**Describe the bug**
If the user writes code in the `OnDocumentError()` handler, and that code throws an exception which is not caught in their code then the pipeline stalls and documents are left undeleted in the service.

**To Reproduce**
Run the following code (updating the document source file path to a folder containing a few documents)

```
var pipeline = await WaivesApi.CreatePipeline(new WaivesOptions
{
     ClientId = ClientId,
     ClientSecret = ClientSecret,
});

var fileSystemDocumentSource = FileSystem.ReadFrom(@"F:\demo\classification-mortgages\test");

pipeline.WithDocumentsFrom(fileSystemDocumentSource)
        .ClassifyWith("mortgages")
        .Then(d =>
        {
             throw new Exception("ThenException");
         })
         .OnDocumentError(d =>
         {
              throw new Exception("OnDocumentErrorException");
          })

          pipeline.Start();
```

**Expected behaviour**
~~The user-thrown exception is caught by the SDK and logged as an error, but otherwise processing continues as normal.~~
The document is deleted, and the pipeline halts execution. It's left to the consuming application to provide a resilient error handler operation.

**System details(please complete the following information):**
 - SDK version: commit 41f244e

**Comment by alastairs** [comment] 2019-09-23 20:33
Interestingly, this appears to be expected behaviour as far as the current code is concerned; we even have [a test for it](https://github.com/waives/waives.net/blob/master/test/Waives.Pipelines.Tests/PipelineFacts.cs#L374). We do need to tidy up the document that caused the error, though; I think any other currently-processing will succeed or fail independently of the original one, but that is also TBC.

**Comment by alastairs** [comment] 2019-09-23 20:40
It also occurs to me that if `OnDocumentError` is invoked because of a network error, it's probable that attempting to delete the document then will also fail. [We already make a best-effort attempt at deleting the document when processing fails.](https://github.com/waives/waives.net/blob/master/src/Waives.Pipelines/ObservableProcessExtension.cs#L35)

I _think_ this might be a wontfix.

**Comment by alastairs** [comment] 2019-09-25 16:34
Further investigation has highlighted the following:

* The current behaviour is as described, and undesirable: the pipeline ends up in what appears to be a deadlock state. This is because `IObserver<T>`'s assumption is that `OnError()` is fatal, and Rx enforces that.
* The `PipelineException` thrown in `PipelineObserver.OnError()` is not surfacing on the main thread.

This is not a wontfix. It overlaps with #15 and #62.

**Closed** 2019-09-30 13:18 UTC
Labels: bug
